# Working with Text data
  ## Tokeniizing text


In [1]:
import os
import urllib.request

if not os.path.exists("verdict.txt"):
    url +("https://github.com/rasbt/LLMs-from-scratch/blob/main/ch02/01_main-chapter-code/the-verdict.txt")
    file_path="verdict.txt"
    urlib.requests.urlretrieve(url,file_path)

In [2]:
with open ("verdict.txt", "r", encoding="utf-8") as f:
    raw_text=f.read()

In [3]:
raw_text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [4]:
len(raw_text)

20479

In [5]:
import re
#  for now we using regex but later will use tiktoken for the tokenistation
#  simple using regex to split on white space 
text=raw_text
result=re.split(r'([,.:;?_!"()\']|--|\s)',text)

In [6]:
result

['I',
 ' ',
 'HAD',
 ' ',
 'always',
 ' ',
 'thought',
 ' ',
 'Jack',
 ' ',
 'Gisburn',
 ' ',
 'rather',
 ' ',
 'a',
 ' ',
 'cheap',
 ' ',
 'genius',
 '--',
 'though',
 ' ',
 'a',
 ' ',
 'good',
 ' ',
 'fellow',
 ' ',
 'enough',
 '--',
 'so',
 ' ',
 'it',
 ' ',
 'was',
 ' ',
 'no',
 ' ',
 'great',
 ' ',
 'surprise',
 ' ',
 'to',
 ' ',
 'me',
 ' ',
 'to',
 ' ',
 'hear',
 ' ',
 'that',
 ',',
 '',
 ' ',
 'in',
 ' ',
 'the',
 ' ',
 'height',
 ' ',
 'of',
 ' ',
 'his',
 ' ',
 'glory',
 ',',
 '',
 ' ',
 'he',
 ' ',
 'had',
 ' ',
 'dropped',
 ' ',
 'his',
 ' ',
 'painting',
 ',',
 '',
 ' ',
 'married',
 ' ',
 'a',
 ' ',
 'rich',
 ' ',
 'widow',
 ',',
 '',
 ' ',
 'and',
 ' ',
 'established',
 ' ',
 'himself',
 ' ',
 'in',
 ' ',
 'a',
 ' ',
 'villa',
 ' ',
 'on',
 ' ',
 'the',
 ' ',
 'Riviera',
 '.',
 '',
 ' ',
 '',
 '(',
 'Though',
 ' ',
 'I',
 ' ',
 'rather',
 ' ',
 'thought',
 ' ',
 'it',
 ' ',
 'would',
 ' ',
 'have',
 ' ',
 'been',
 ' ',
 'Rome',
 ' ',
 'or',
 ' ',
 'Florence',
 '.',
 '',


In [7]:
#  stripping whitespace
result= [item for item in result if item.strip()]
result

['I',
 'HAD',
 'always',
 'thought',
 'Jack',
 'Gisburn',
 'rather',
 'a',
 'cheap',
 'genius',
 '--',
 'though',
 'a',
 'good',
 'fellow',
 'enough',
 '--',
 'so',
 'it',
 'was',
 'no',
 'great',
 'surprise',
 'to',
 'me',
 'to',
 'hear',
 'that',
 ',',
 'in',
 'the',
 'height',
 'of',
 'his',
 'glory',
 ',',
 'he',
 'had',
 'dropped',
 'his',
 'painting',
 ',',
 'married',
 'a',
 'rich',
 'widow',
 ',',
 'and',
 'established',
 'himself',
 'in',
 'a',
 'villa',
 'on',
 'the',
 'Riviera',
 '.',
 '(',
 'Though',
 'I',
 'rather',
 'thought',
 'it',
 'would',
 'have',
 'been',
 'Rome',
 'or',
 'Florence',
 '.',
 ')',
 '"',
 'The',
 'height',
 'of',
 'his',
 'glory',
 '"',
 '--',
 'that',
 'was',
 'what',
 'the',
 'women',
 'called',
 'it',
 '.',
 'I',
 'can',
 'hear',
 'Mrs',
 '.',
 'Gideon',
 'Thwing',
 '--',
 'his',
 'last',
 'Chicago',
 'sitter',
 '--',
 'deploring',
 'his',
 'unaccountable',
 'abdication',
 '.',
 '"',
 'Of',
 'course',
 'it',
 "'",
 's',
 'going',
 'to',
 'send',
 't

In [8]:
preprocessed=result
len(preprocessed)

4690

# converting token into token id

 

In [9]:
all_words=sorted(set(preprocessed))
vocab_size=len(all_words)

In [10]:
vocab= {token:integer for integer , token in enumerate (all_words)}
vocab

{'!': 0,
 '"': 1,
 "'": 2,
 '(': 3,
 ')': 4,
 ',': 5,
 '--': 6,
 '.': 7,
 ':': 8,
 ';': 9,
 '?': 10,
 'A': 11,
 'Ah': 12,
 'Among': 13,
 'And': 14,
 'Are': 15,
 'Arrt': 16,
 'As': 17,
 'At': 18,
 'Be': 19,
 'Begin': 20,
 'Burlington': 21,
 'But': 22,
 'By': 23,
 'Carlo': 24,
 'Chicago': 25,
 'Claude': 26,
 'Come': 27,
 'Croft': 28,
 'Destroyed': 29,
 'Devonshire': 30,
 'Don': 31,
 'Dubarry': 32,
 'Emperors': 33,
 'Florence': 34,
 'For': 35,
 'Gallery': 36,
 'Gideon': 37,
 'Gisburn': 38,
 'Gisburns': 39,
 'Grafton': 40,
 'Greek': 41,
 'Grindle': 42,
 'Grindles': 43,
 'HAD': 44,
 'Had': 45,
 'Hang': 46,
 'Has': 47,
 'He': 48,
 'Her': 49,
 'Hermia': 50,
 'His': 51,
 'How': 52,
 'I': 53,
 'If': 54,
 'In': 55,
 'It': 56,
 'Jack': 57,
 'Jove': 58,
 'Just': 59,
 'Lord': 60,
 'Made': 61,
 'Miss': 62,
 'Money': 63,
 'Monte': 64,
 'Moon-dancers': 65,
 'Mr': 66,
 'Mrs': 67,
 'My': 68,
 'Never': 69,
 'No': 70,
 'Now': 71,
 'Nutley': 72,
 'Of': 73,
 'Oh': 74,
 'On': 75,
 'Once': 76,
 'Only': 77,
 '

In [11]:
#  a simple tokenizer how works the not the real one like gpt 
class SimpleTokenizerV1:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str={i:s for s, i in vocab.items()}

    def encode(self,text):
        preprocessed=re.split(r'([,.:;?_!"()\']|--|\s)',text)

        preprocessed= [
            item.strip() for item in preprocessed if item.strip()
        ]

        ids= [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self,ids):
        text= " ".join([self.int_to_str[i] for i in ids])
        #  replace space before the specified punctuation
        text=re.sub(r'\s+([,.?!"()\'])',r'\1',text)
        return text

In [12]:
tokenizer=SimpleTokenizerV1(vocab)

In [13]:
ids=tokenizer.encode(raw_text)

# Adding special Context tokens

In [14]:
#  it gives erroor becoause the above text we used to create token as we do not ahve the hello word in that 
# so  we will  try to handle the words which are not in token 
text="Hello, do you like tea. is this-- a test?"
tokenizer.encode(text)

KeyError: 'Hello'

In [15]:
all_tokens= sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab={token:integer for integer,token in enumerate(all_tokens)}

In [16]:
len(vocab.items())

1132

In [17]:
for i,item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [18]:
#  modifyingh our tokenizeer so it not crash on the word which is not in vocab
class SimpleTokenizerV2:
    def __init__(self,vocab):
        self.str_to_int=vocab
        self.int_to_str={i:s for s, i in vocab.items()}

    def encode(self,text):
        preprocessed=re.split(r'([,.:;?_!"()\']|--|\s)',text)

        preprocessed= [
            item.strip() for item in preprocessed if item.strip()
        ]
#  for the handling unknown word
        preprocessed= [
            item if item in self.str_to_int
            else  "<|unk|>" for item in preprocessed
            
        ]

        ids= [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self,ids):
        text= " ".join([self.int_to_str[i] for i in ids])
        #  replace space before the specified punctuation
        text=re.sub(r'\s+([,.?!"()\'])',r'\1',text)
        return text

#  it has shortcomming is lke for unknowd or new token ahs <|unk|> which like no one does know what is this or what it means

In [19]:
tokenizer=SimpleTokenizerV2(vocab)

In [20]:
tokenizer.encode(text)

[1131, 5, 355, 1126, 628, 975, 7, 584, 999, 6, 115, 1131, 10]

In [21]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea. is this -- a <|unk|>?'

 # Byte pair encoding 
 ## it is algo for handling unknown tokens 
 - llama3 uses it gpt does it too
gpt2 used --  https://github.com/openai/gpt-2/blob/master/src/encoder.py

- we will  use library tiktoken -- https://github.com/openai/tiktoken for tokinisation

   

In [22]:
import tiktoken 

In [23]:
tiktoken.__version__

'0.14.0'

In [68]:
tokenizer = tiktoken.get_encoding("o200k_base") # it has pretrained gpt2 encoder so nothing to worry
#  it works like as we tried to do our own so name are smae and methods implemnetation differs

In [69]:

text=(
    "hello, do you  like tea ? <|endoftext|> In the  sunlit terraces"
    "of someunknown place fasdfaferfff"
)
# tokenizer.encode(text) # we get error becoz that <|endoftext|> is special token or marker used to mark end of the doc 
# usually used end of the doc or the begninng of doc to mark the start and of diffrenct  file
# by default it is disabled we enable by using it like below
#  it work with arbitrary text but that is special token so we need to include it
tokenizer.encode(text,allowed_special={"<|endoftext|>"})

[24912,
 11,
 621,
 481,
 220,
 1299,
 17966,
 1423,
 220,
 199999,
 730,
 290,
 220,
 7334,
 32758,
 173297,
 1440,
 1236,
 33936,
 2475,
 36602,
 168770,
 855,
 29318]

# Data sampling with sliding window
- We train LLMs to generate one word at a time, so we want to prepare the training data accordingly where the next word in a sequence represents the target to predict:

In [70]:
enc_text=tokenizer.encode(raw_text)
print(len(enc_text))

4836


In [71]:
enc_sample=enc_text[50:]
#  llm can't proacess all token at a time so we pass in chunks 

### For each text chunk, we want the inputs and targets
Since we want the model to predict the next word, the targets are the inputs shifted by one position to the right

In [72]:
#  how we prepare x  input y output
#  it is like when a token or more token given then which one to predict 
context_size=4
x=enc_sample[:context_size]
y=enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y: {y}")

x: [11166, 306, 261, 38350]
y: [306, 261, 38350, 402]


In [73]:
#  to be more visual for the above predicting token



for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

#  one by one prediction will look like this 

 himself ---->  in
 himself in ---->  a
 himself in a ---->  villa
 himself in a villa ---->  on


In [74]:
import torch


In [75]:
torch.__version__

'2.11.0+cu128'

In [76]:
from torch.utils.data import Dataset, DataLoader


class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]



In [77]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("o200k_base")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [78]:
#  this is for demo batch size 1 
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=4, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[    40, 148954,   3324,   4525]]), tensor([[148954,   3324,   4525,  10874]])]


In [79]:
sec_batch = next(data_iter)
print(sec_batch)

[tensor([[ 10874, 165003,  33750,   7542]]), tensor([[165003,  33750,   7542,    261]])]


In [80]:
#  using higher batch size
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[    40, 148954,   3324,   4525],
        [ 10874, 165003,  33750,   7542],
        [   261,  12424,  59245,    375],
        [  6460,    261,   1899,  19807],
        [  4951,    375,    786,    480],
        [   673,    860,   2212,  19005],
        [   316,    668,    316,   9598],
        [   484,     11,    306,    290]])

Targets:
 tensor([[148954,   3324,   4525,  10874],
        [165003,  33750,   7542,    261],
        [ 12424,  59245,    375,   6460],
        [   261,   1899,  19807,   4951],
        [   375,    786,    480,    673],
        [   860,   2212,  19005,    316],
        [   668,    316,   9598,    484],
        [    11,    306,    290,   4679]])


## Creating token Embeddings

In [81]:
input_ids = torch.tensor([2, 3, 5, 1])

In [82]:
vocab_size=6
output_dim=3

# torch.manual_seed(123) # it is for everytime we run code we do not get diffrent output
embedding_layer=torch.nn.Embedding(tokenizer.n_vocab,output_dim)

In [83]:
print(embedding_layer.weight)

Parameter containing:
tensor([[-0.6224,  2.0837,  1.0277],
        [ 0.0097, -0.9304,  0.7659],
        [ 0.4644,  1.0495, -1.7692],
        ...,
        [ 1.9287, -0.1189, -1.5653],
        [-3.1017, -1.3112,  0.6847],
        [ 0.0177, -0.6354, -0.5438]], requires_grad=True)


In [84]:
print(embedding_layer(torch.tensor([3])))

tensor([[ 0.1206, -0.7943, -0.7570]], grad_fn=<EmbeddingBackward0>)


In [85]:
embedding_layer(input_ids)

tensor([[ 0.4644,  1.0495, -1.7692],
        [ 0.1206, -0.7943, -0.7570],
        [-0.4561, -1.0580,  0.6797],
        [ 0.0097, -0.9304,  0.7659]], grad_fn=<EmbeddingBackward0>)

# Encoding word positions

In [87]:
vocab_size=200019
output_dim=256

token_embeddin_layer= torch.nn.Embedding(vocab_size,output_dim)


In [88]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [90]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[    40, 148954,   3324,   4525],
        [ 10874, 165003,  33750,   7542],
        [   261,  12424,  59245,    375],
        [  6460,    261,   1899,  19807],
        [  4951,    375,    786,    480],
        [   673,    860,   2212,  19005],
        [   316,    668,    316,   9598],
        [   484,     11,    306,    290]])

Inputs shape:
 torch.Size([8, 4])


In [91]:
token_embeddings=token_embeddin_layer(inputs)
token_embeddings.shape

torch.Size([8, 4, 256])

In [93]:
# printing the first token id of 256 dimensional vector of first batch
token_embeddings[0,0]

tensor([ 4.4151e-01, -1.0667e+00,  4.6739e-01, -2.1684e+00, -6.0209e-01,
        -4.5443e-01, -5.0658e-01, -1.1494e+00,  5.5896e-01, -2.6824e-01,
         1.1409e+00,  1.1226e-01, -1.3775e-01,  1.7541e-01,  1.1786e+00,
        -9.8660e-01, -1.1200e+00, -2.8201e-01,  1.1439e+00, -1.6820e-01,
        -5.0801e-01, -1.7937e+00, -6.8228e-02,  8.3546e-02, -2.0777e-01,
        -6.4805e-01, -3.9252e-01, -7.7683e-01, -6.5343e-01,  1.2469e+00,
         5.9539e-01,  1.6413e-02,  2.8325e-01,  3.0034e-01,  4.9123e-01,
        -1.8729e-01, -1.1255e+00, -4.0098e-01, -1.4976e+00, -2.1081e-02,
        -2.4727e+00, -1.0656e+00, -4.8178e-01,  1.2814e-01, -6.2156e-01,
        -2.6081e+00,  1.4658e-01,  9.5746e-01, -1.3232e+00,  1.5914e+00,
         1.1763e-01, -1.2359e+00, -7.8379e-01, -3.4301e-01,  3.0966e-01,
        -1.8837e+00,  1.4002e+00, -2.6091e-01,  3.5451e-01, -9.5727e-01,
        -1.6931e-01, -4.9237e-01, -3.3981e-01,  3.4911e-01,  4.3587e-01,
        -6.9161e-01, -3.0126e-01, -6.3213e-01, -6.5

In [94]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [95]:
torch.arange(max_length)

tensor([0, 1, 2, 3])

In [96]:
pos_embedding_layer.weight

Parameter containing:
tensor([[-0.4550,  0.5999, -0.0380,  ...,  0.3925,  1.0561, -0.8731],
        [ 0.0611, -0.8658,  1.3917,  ..., -0.5196, -0.7205, -0.3845],
        [-0.5992,  2.0505, -0.4188,  ..., -1.4840,  0.4735,  0.3668],
        [-0.3387,  0.2955,  0.5002,  ...,  2.5064, -1.2770,  0.8709]],
       requires_grad=True)

In [98]:
pos_embeddings= pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [99]:
token_embeddings.shape

torch.Size([8, 4, 256])

In [100]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])


In [101]:
print(input_embeddings)

tensor([[[-0.0135, -0.4667,  0.4294,  ..., -1.2433,  2.8852, -1.5727],
         [ 0.1866, -1.4047,  1.7493,  ...,  0.6125, -0.1624,  1.4054],
         [ 0.6248,  3.0668, -1.0660,  ..., -2.7562,  1.4493,  1.9446],
         [-1.0585,  0.6573,  1.2441,  ...,  2.1023, -2.4777, -0.0543]],

        [[-0.5663,  1.5873, -0.9568,  ...,  0.8086,  1.6281,  0.5731],
         [-0.1875, -0.2367,  1.3218,  ..., -1.6881, -0.6992,  0.5179],
         [-0.8940,  1.3794,  0.4056,  ..., -3.0457,  1.8064, -0.6113],
         [-0.2746, -0.2492,  0.2235,  ...,  2.0202, -2.6173,  2.4628]],

        [[-1.1253,  1.9446,  1.0943,  ...,  0.0594,  1.3865,  0.0158],
         [ 0.9533, -0.8155,  2.3138,  ..., -0.7474, -2.6178, -0.2030],
         [-1.0576,  2.5817, -0.3250,  ..., -1.6750, -0.0306,  0.4581],
         [-0.8039,  0.3115,  0.1010,  ...,  1.2347, -2.3832,  1.2586]],

        ...,

        [[-0.7442, -0.3778,  1.1462,  ...,  2.4751,  2.4733, -1.3718],
         [-0.3827,  0.4571,  1.5658,  ...,  0.2626, -0.08